### ISSUE TITLE
I get the following error when creating the SimpleStore using nodejs

### ISSUE THREAD

**Issue by Raathmd** [runonbitcoin/sdk#1]
TypeError: Cannot read property 'Random' of undefined
    at new m (/Users/mscs/SimpleStore/dist/run.node.min.js:1:28389)

**Comment by brentongunning** [comment]
Hi Raathmd,

This error happens when you are using version 2 of the `bsv` library. Run currently requires v1. Downgrading `bsv` should fix it:

```
npm uninstall bsv
npm install bsv@1.5.4
```

If you have code that relies on bsv 2, then installing Run from NPM will let you use both bsv libraries side by side.

Let me know if it fixes it. We'll add a better error message for the next person.

**Comment by Raathmd** [comment]
resolved - import Run from 'run-sdk';

**Comment by Raathmd** [comment]
I solved finding the module by using the import statement. After this, i stopped getting the reference to Random property.
The error did, however, occur when I had the 'run.node.min' in the current directory.
I will also downgrade the BSV lib.
Thanks
