### ISSUE TITLE
64: too-long-mempool-chain on mainnet

### ISSUE THREAD

**Issue by Raathmd** [runonbitcoin/sdk#2]
This error occurred when my purse balance went too low. 
Is this the correct error?

POST https://api.run.network/v1/main/tx

64: too-long-mempool-chain
    at /Users/mscs/Desktop/SimpleStore/node_modules/run-sdk/dist/run.node.min.js:1:69357
    at H (/Users/mscs/Desktop/SimpleStore/node_modules/run-sdk/dist/run.node.min.js:1:69370)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.func (/Users/mscs/Desktop/SimpleStore/node_modules/run-sdk/dist/run.node.min.js:1:62594)
    at async t.exports.la (/Users/mscs/Desktop/SimpleStore/node_modules/run-sdk/dist/run.node.min.js:1:140516)

**Comment by brentongunning** [comment]
Hi Raathmd,

Were you creating a lot of transactions over a short time? If so, it probably was the correct error. 

The *too-long-mempool-chain* error happens when a particular bitcoin output is spent too quickly. Run tries to avoid this error by automatically splitting your bitcoins into different outputs. However, when you have a low purse balance, this splitting strategy doesn't always work. I suspect that's what happened here. Fortunately, the Bitcoin SV node team is [already fixing the root problem](https://bitcoinsv.io/2020/12/24/a-belated-christmas-present-from-bitcoin-sv-team/), and it should be a non-issue by next month.

Until then, I recommend increasing your purse balance first. Then, if you are creating a lot of transactions and still seeing the error, you can increase the number of splits, from the default value of 10 to something higher like 50: `run.purse.splits = 50`.

**Comment by brentongunning** [comment]
Closing b/c this is probably the right error
