### ISSUE TITLE
hello ,could you share the sdk source before compress it

### ISSUE THREAD

**Issue by flufy3d** [runonbitcoin/sdk#4]
and could you tell me how you compute the out hashs?

out | State hashes of jigs and code in transaction outputs

thanks

**Comment by brentongunning** [comment]
Hi @flufy3d,

We're going to be releasing all of the source code this year. First we've got some other work to do, but it's coming.

To answer your question, the state hashes in `out` and `del` are calculated via `sha256(state)`. The state is a data structure that captures the jig at a moment in time. It's what gets stored in the cache. Let me give an example.

**Example**

Here is a jig:

```
const location = '4f86f5d80906bbb1faa891327411925fa56e6eaa1e197bef63e9dcb3a0e406e0_o1'
```

<a href="https://run.network/explorer/?query=4f86f5d80906bbb1faa891327411925fa56e6eaa1e197bef63e9dcb3a0e406e0_o1&network=main"><img src="https://run.network/lessons/mockchain-jig-web-console/images/search-dragon.png" width="400"></a>

The *state hash* is the first entry of `out` in the transaction metadata. You can get the hash:

```
const run = new Run({ network: 'main' })
const txid = location.slice(0, 64)
const rawtx = await run.blockchain.fetch(txid)
const metadata = Run.util.metadata(rawtx)
const stateHash = metadata.out[0]
console.log(stateHash)
```

> 45fbdd23dd545a0c68afeb65803be7426791f5900b73a6dd6ffc53cc710a0d24

The *state*, from which that was calculated, is stored in the cache. You can get the state:

```
const state = await run.cache.get('jig://' + location)
console.log(JSON.stringify(state))
```

> {"cls":{"$jig":"f49322b741816a1c62a170833b222e3486ec7bd0cb839c4d4f194eba68a1e772_o1"},"kind":"jig","props":{"age":5,"location":"_o1","name":"Spot","nonce":1,"origin":"_o1","owner":"19vftvbSiz5QbLPnQTTscRMP9LU5Vozt1H","satoshis":0},"version":"04"}

If you take the sha256 of the state, you get the state hash:

```
const stateBuffer = bsv.deps.Buffer.from(JSON.stringify(state), 'utf8')
const stateHash = bsv.crypto.Hash.sha256(stateBuffer)
console.log(stateHash.toString('hex'))
```

> 45fbdd23dd545a0c68afeb65803be7426791f5900b73a6dd6ffc53cc710a0d24

Set that the hashes match.

Different jigs of course will have different states, and this will all be documented eventually. But give it a try with a few jigs and you'll pick it up.

**Comment by flufy3d** [comment]
![image](https://user-images.githubusercontent.com/1730604/106278853-b7224100-623b-11eb-895e-c68034b90844.png)

I can't find any signature data, will this be a problem?

like this one

https://run.network/explorer/?query=fd5bd64ec3fa2e5e4efbea162b98461e29d61cd82727ad8ae82d8c01dc9bece5_o1&network=main

I can create dragon object even I don't have owner private key

**Comment by brentongunning** [comment]
I was wondering who was sending jigs to the tutorial address 😊 

Yes, that Dragon class lets you create jigs for other users  — by its design. Whether this is a problem or not depends on your application and if you want to allow that. You can write your jig class in a way so that signatures *are* required to create instances if you want. The two techniques are the [`auth()` method](https://run.network/docs/#advanced-usage-auth-method) and [minter jigs](https://run.network/docs/#tips-and-tricks-limiting-supply). Also, you'll always need signatures to update jigs or to create jigs from other jigs.

I do like the idea of requiring signatures for all creations in the future though. We'll probably do that. It's more intuitive, and also will unlock some other features, but it'll require a protocol change to put signatures in the `op_return`.
